Lab3/Lab3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('Lab3App.urls'))
]

Lab3/Lab3App/urls.py
from django.conf.urls import url, include

from . import views

app_name = 'Lab3App'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^api/facts/', include([
        url(r'^$', views.all_facts, name='facts'),
        url(r'^(?P<id>[0-9]+)/$', views.fact, name='fact')
    ])),
    url(r'^api/dimensions_names/$', views.get_dim_names_ids, name='dimensions_names'),
    url(r'^api/search/', include([
        url(r'^projects/$', views.bool_search, name='bool_search'),
        url(r'^customers/$', views.range_search, name='range_search')
    ])),
    url(r'^history/$', views.HistoryView.as_view(), name='history')
]

Lab3/Lab3App/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey has `on_delete` set to the desired behavior.
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from __future__ import unicode_literals

from django.db import models


class ChangesProjectStatus(models.Model):
    id_changing = models.AutoField(primary_key=True)
    id_project = models.ForeignKey('Projects', models.DO_NOTHING, db_column='id_project', blank=True, null=True)
    id_customer = models.ForeignKey('Customers', models.DO_NOTHING, db_column='id_customer', blank=True, null=True)
    id_team = models.ForeignKey('Teams', models.DO_NOTHING, db_column='id_team', blank=True, null=True)
    changing_date = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'changes_project_status'


class Customers(models.Model):
    id_customer = models.IntegerField(primary_key=True)
    customer_name = models.CharField(max_length=256, blank=True, null=True)
    customer_email = models.CharField(max_length=256, blank=True, null=True)
    customer_phone = models.CharField(max_length=256, blank=True, null=True)
    invitings_date = models.DateField(blank=True, null=True)

    class Meta:
        db_table = 'customers'


# class DjangoMigrations(models.Model):
#     app = models.CharField(max_length=255)
#     name = models.CharField(max_length=255)
#     applied = models.DateTimeField()
#
#     class Meta:
#         db_table = 'django_migrations'


class Projects(models.Model):
    id_project = models.AutoField(primary_key=True)
    project_name = models.CharField(max_length=256, blank=True, null=True)
    project_description = models.TextField(blank=True, null=True)
    finish_status = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'projects'


class Teams(models.Model):
    id_team = models.AutoField(primary_key=True)
    team_name = models.CharField(max_length=256, blank=True, null=True)
    team_department = models.CharField(max_length=256, blank=True, null=True)
    manager_name = models.CharField(max_length=256, blank=True, null=True)
    developers = models.IntegerField(blank=True, null=True)

    class Meta:
        db_table = 'teams'


class History(models.Model):
    id = models.AutoField(db_column='Id', primary_key=True)
    changes_project_status_id = models.IntegerField(db_column='Changes_project_status_id')
    projectHistory = models.CharField(db_column='ProjectHistory', max_length=80, blank=True, null=True)
    customerHistory = models.CharField(db_column='CustomerHistory', max_length=80, blank=True, null=True)
    teamHistory = models.CharField(db_column='TeamHistory', max_length=80, blank=True, null=True)
    date = models.DateTimeField(db_column='Date')

    class Meta:
        db_table = 'History'

Lab3/Lab3App/views.py
import datetime
import ast
from django.http import JsonResponse
from django.views import generic
from .models import *
from django.apps import apps


class IndexView(generic.ListView):
    template_name = 'Lab3App/index.html'

    def get_queryset(self):
        pass


class HistoryView(generic.ListView):
    template_name = 'Lab3App/history.html'
    context_object_name = 'history_list'

    def get_queryset(self):
        return History.objects.order_by('-date')


def all_facts(request):

    if request.method == 'GET':
        return get_all_facts(request)
    elif request.method == 'POST':
        return post_fact(request)
    elif request.method == 'DELETE':
        return delete_facts(request)

def get_all_facts(request):
    facts_q = get_facts()

    res = dict({
        'facts': list(facts_q)
    })
    return JsonResponse(res)

def post_fact(request):
    dataStr = request.body.decode('utf-8')
    fact = ast.literal_eval(dataStr)
    instance = ChangesProjectStatus(
        id_project=Projects.objects.get(id_project=fact['id_project']),
        id_customer = Customers.objects.get(id_customer=fact['id_customer']),
        id_team = Teams.objects.get(id_team=fact['id_team']),
        changing_date=str(datetime.date.today())
    )
    ''''newFact = ChangesProjectStatus.objects.create(Projects.objects.filter(id_project = fact['id_project']),
                            Customers.objects.filter(id_customer = fact['id_customer']), Teams.objects.filter(id_team = fact['id_team']), changing_date = str(datetime.date.today()))

    newFact = get_facts(newFact.id_changing)
    print(newFact)
    '''''
    instance.save()
    res = dict({
        'fact': list(ChangesProjectStatus.objects.filter(id_changing=instance.id_changing).values('id_changing', 'id_project__project_name', 'id_team__team_name', 'id_customer__customer_name', 'changing_date').order_by('id_changing'))[0]
    })
    return JsonResponse(res)

def delete_facts(request):
    ChangesProjectStatus.objects.all().delete()
    res = dict({'status':True})
    return JsonResponse(res)

def fact(request, id):
    if request.method == 'PUT':
        return put_fact(request, id)
    elif request.method == 'DELETE':
        return delete_fact(request, id)

def put_fact(request, id):
    dataStr = request.body.decode('utf-8')
    fact = ast.literal_eval(dataStr)
    ChangesProjectStatus.objects\
        .filter(id_changing=int(id))\
        .update(
        id_project=Projects.objects.get(id_project=fact['id_project']),
        id_customer=Customers.objects.get(id_customer=fact['id_customer']),
        id_team=Teams.objects.get(id_team=fact['id_team']),
        changing_date=datetime.date.today()
    )

    newFact = get_facts(id)
    print(newFact)
    res = dict({'fact': list(newFact)[0]})
    return JsonResponse(res)

def delete_fact(request, id):
    ChangesProjectStatus.objects.filter(id_changing=int(id)).delete()
    res = dict({'status':'OK'})
    return JsonResponse(res)



def bool_search(request):
    if request.method == 'GET':
        finish_status = request.GET.get('finish_status')

        projects = Projects.objects.filter(finish_status=finish_status).values()

        res = dict({'projects':list(projects)})
        return JsonResponse(res)

def range_search(request):
    if request.method == 'GET':
        bottom = request.GET.get('bottom')
        top = request.GET.get('top')

        customers = Customers.objects.filter(invitins_date__range=[bottom,top]).values()

        res = dict({'customers':list(customers)})
        return JsonResponse(res)

def get_dim_names_ids(request):

    projects = get_all_id_name_dim("Projects")
    customers = get_all_id_name_dim("Customers")
    teams = get_all_id_name_dim("Teams")

    res = dict({
        'data': {
            'projects': projects,
            'customers': customers,
            'teams': teams
        }
    })

    return JsonResponse(res)

def get_all_id_name_dim(dim_name):
    Dimension = apps.get_model('Lab3App', dim_name)
    if(dim_name == 'Projects'):
        return list(Dimension.objects.values('id_project', 'project_name'))
    if(dim_name == 'Customers'):
        return list(Dimension.objects.values('id_customer', 'customer_name'))
    if(dim_name == 'Teams'):
        return list(Dimension.objects.values('id_team', 'team_name'))


def get_facts(id=None):
    if id is None:
        return ChangesProjectStatus.objects.values('id_changing', 'id_project__project_name', 'id_team__team_name', 'id_customer__customer_name', 'changing_date').order_by('id_changing')

    else:
        return ChangesProjectStatus.objects.filter(id_changing=int(id)).values('id_changing', 'id_project__project_name', 'id_team__team_name', 'id_customer__customer_name', 'changing_date')

Lab3/Lab3App/templates/Lab3App/history.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>History</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body background="/static/Lab3App/background.jpg">
<div class="container">
    <ul class="pager">
        <li class="previous"><a href="{% url 'Lab3App:index' %}">Film creations</a></li>
    </ul>
    {% if history_list %}
        <div class="table-responsive">
            <table class="table well">
                <thead>
                <tr>
                    <th class="col-md-1">#</th>
                    <th class="col-md-1">PC</th>
                    <th>Project</th>
                    <th>Customer</th>
                    <th>Team</th>
                    <th>Datetime</th>
                </tr>
                </thead>
                <tbody>
                {% for history in history_list %}
                    <tr>
                        <td>{{ history.id }}</td>
                        <td>{{ history.changes_project_status_id }}</td>
                        <td>{{ history.projectHistory }}</td>
                        <td>{{ history.customerHistory }}</td>
                        <td>{{ history.teamHistory }}</td>
                        <td>{{ history.date }}</td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    {% else %}
        <div class="alert alert-info text-center">
            <strong>Info!</strong> No history elements. Turn on history switcher and change smth.
        </div>
    {% endif %}
</div>
</body>
</html>

Lab3/Lab3App/templates/Lab3App/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <title>Films</title>

        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/mustache.js/2.3.0/mustache.min.js"></script>
    </head>

    <body background="/static/Lab3App/back.jpg" ">

         <div class="container">
             <div class="jumbotron">

                 <h1 class="text-center">Changing project status</h1>
             </div>
             <ul class="pager">
                 <li class="next"><a href="{% url 'Lab3App:history' %}">History</a></li>
             </ul>
             <table  class="table table-bordered table-hover well"
                     style="border-radius: 15px; border-width: 0px">
                 <thead>
                 <tr>
                     <th class="col-md-1">#</th>
                     <th >Project</th>
                     <th >Customer</th>
                     <th >Team</th>
                     <th >Changing date</th>
                     <th class="col-md-3">Action</th>
                 </tr>
                 </thead>
                 <tbody id="factsTable"></tbody>
             </table>

             <div class="row">
                 <div class="col-md-4 text-center">
                     <button id="newInstanceBtn" type="button" class="btn btn-primary btn-lg"
                             data-toggle="modal" data-target="#cuModal">
                         Add instance
                     </button>
                 </div>
                 <div class="col-md-6 text-center">
                     <button id="truncateBtnModal" type="button" class="btn btn-danger btn-lg"
                             data-toggle="modal" data-target="#deletingModal">
                         Delete table
                     </button>
                 </div>
             </div>

             <hr>
             <div class="panel panel-group panel-primary">
                <div class="panel-heading text-center">Search</div>
                <div class="panel-body">
                    <div class="panel-group" id="accordion">
                        <div class="panel panel-default"><!--BOOL SEARCH-->
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a href="#collapseBoolSearch" data-parent="#accordion" data-toggle="collapse">
                                        Bool search
                                    </a>
                                </h3>
                            </div>
                            <div id="collapseBoolSearch" class="panel-collapse collapse">
                                <div class="panel-body">
                                    Find projects which
                                    <select id="finished">
                                        <option value="1">finished</option>
                                        <option value="0">developing</option>
                                    </select> <br/><br/>
                                    <button id="searchFinished" class="btn btn-default" type="submit">
                                        Search
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                    <hr>
                                    <table  id="searchFinishedTable" class="table table-bordered table-hover well" style="display: none">
                                        <thead>
                                        <tr>
                                            <th class="col-md-1">#</th>
                                            <th >Name</th>
                                            <th class="col-md-6">Description</th>
                                        </tr>
                                        </thead>
                                        <tbody id="searchFinishTBody"></tbody>
                                    </table>
                                </div>
                            </div>
                        </div><!--BOOL SEARCH-->
                        <div class="panel panel-default"><!--Date ranges search-->
                            <div class="panel-heading">
                                <h3 class="panel-title">
                                    <a href="#collapseNumRangeSearch" data-parent="#accordion" data-toggle="collapse">
                                        Date range search
                                    </a>
                                </h3>
                            </div>
                            <div id="collapseNumRangeSearch" class="panel-collapse collapse">
                                <div class="panel-body">
                                    Find customers with invitings date between
                                    <input type="date" id="bottomVal">
                                    and
                                    <input type="date" id="topVal">
                                    <br/>
                                    <button id="searchRange" class="btn btn-default" type="submit">
                                        Search
                                        <i class="glyphicon glyphicon-search"></i>
                                    </button>
                                    <hr>
                                    <table  id="searchRangeTable" class="table table-bordered table-hover well" style="display: none">
                                        <thead>
                                        <tr>
                                            <th class="col-md-1">#</th>
                                            <th >Name</th>
                                            <th >Email</th>
                                            <th >Invitings date</th>
                                        </tr>
                                        </thead>
                                        <tbody id="searchRangeTBody"></tbody>
                                    </table>
                                </div>
                            </div>
                        </div><!--DATE RANGE SEARCH-->
                    </div>
                </div>
            </div>
         </div>

         <div id="modalTarget"></div>

    </body>
        <script src="/static/Lab3App/Javascript/index.js"></script>

</html>